# Generated by Django 5.2.13 on 2026-05-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.TextField(blank=True),
        ),
    ]
