# Generated by Django 5.2.13 on 2026-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_product_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
