# Generated by Django 5.2.14 on 2026-05-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchase_unit', models.CharField(max_length=50)),
                ('batch_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('batch_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serving_unit', models.CharField(max_length=50)),
                ('yield_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yield_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
